/**
 * @fileoverview Module Configuration
 * 
 * @author Tony Parisi
 */

goog.provide('glam.Modules');
goog.require('glam.Component');
goog.require('glam.Object');
goog.require('glam.Application');
goog.require('glam.Service');
goog.require('glam.Services');
goog.require('glam.AnimationService');
goog.require('glam.Interpolator');
goog.require('glam.KeyFrameAnimator');
goog.require('glam.Transition');
goog.require('glam.TweenService');
goog.require('glam.Behavior');
goog.require('glam.BounceBehavior');
goog.require('glam.FadeBehavior');
goog.require('glam.HighlightBehavior');
goog.require('glam.MoveBehavior');
goog.require('glam.RotateBehavior');
goog.require('glam.ScaleBehavior');
goog.require('glam.Camera');
goog.require('glam.CameraManager');
goog.require('glam.PerspectiveCamera');
goog.require('glam.FirstPersonControls');
goog.require('glam.OrbitControls');
goog.require('glam.FirstPersonControllerScript');
goog.require('glam.PointerLockControllerScript');
goog.require('glam.PointerLockControls');
goog.require('glam.ModelControllerScript');
goog.require('glam.DeviceOrientationControlsCB');
goog.require('glam.DeviceOrientationControllerScript');
goog.require('glam.OculusRiftControls');
goog.require('glam.RiftControllerScript');
goog.require('glam.EventDispatcher');
goog.require('glam.EventService');
goog.require('glam.Graphics');
goog.require('glam.Helpers');
goog.require('glam.Input');
goog.require('glam.Keyboard');
goog.require('glam.Mouse');
goog.require('glam.Gamepad');
goog.require('glam.Picker');
goog.require('glam.PickManager');
goog.require('glam.CylinderDragger');
goog.require('glam.PlaneDragger');
goog.require('glam.SurfaceDragger');
goog.require('glam.ViewPicker');
goog.require('glam.Light');
goog.require('glam.AmbientLight');
goog.require('glam.DirectionalLight');
goog.require('glam.PointLight');
goog.require('glam.SpotLight');
goog.require('glam.Loader');
goog.require('glam.HUDScript');
goog.require('glam.SkyboxScript');
goog.require('glam.SkysphereScript');
goog.require('glam.Prefabs');
goog.require('glam.Decoration');
goog.require('glam.ParticleEmitter');
goog.require('glam.ParticleSystemScript');
goog.require('glam.Composer');
goog.require('glam.Effect');
goog.require('glam.SceneComponent');
goog.require('glam.Billboard');
goog.require('glam.SceneUtils');
goog.require('glam.SceneVisual');
goog.require('glam.Transform');
goog.require('glam.Visual');
goog.require('glam.Script');
goog.require('glam.System');
goog.require('glam.Time');
goog.require('glam.Timer');
goog.require('glam.Viewer');
goog.require('glam.DOM');
goog.require('glam.AnimationElement');
goog.require('glam.ArcElement');
goog.require('glam.BackgroundElement');
goog.require('glam.BoxElement');
goog.require('glam.CameraElement');
goog.require('glam.CircleElement');
goog.require('glam.DOMClassList');
goog.require('glam.ConeElement');
goog.require('glam.ControllerElement');
goog.require('glam.CylinderElement');
goog.require('glam.DOMDocument');
goog.require('glam.EffectElement');
goog.require('glam.GroupElement');
goog.require('glam.DOMInput');
goog.require('glam.LightElement');
goog.require('glam.LineElement');
goog.require('glam.DOMMaterial');
goog.require('glam.MeshElement');
goog.require('glam.DOMElement');
goog.require('glam.CSSParser');
goog.require('glam.DOMParser');
goog.require('glam.ParticlesElement');
goog.require('glam.RectElement');
goog.require('glam.DOMRenderer');
goog.require('glam.SphereElement');
goog.require('glam.SurfaceElement');
goog.require('glam.DOMStyle');
goog.require('glam.TextElement');
goog.require('glam.DOMTransform');
goog.require('glam.TransitionElement');
goog.require('glam.DOMTypes');
goog.require('glam.DOMViewer');
goog.require('glam.VisualElement');

/**
 * @constructor
 */
glam.Modules = function()
{
}

var CLOSURE_NO_DEPS = true;

